<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQC2HkhK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQC2HkhK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQC2HkhK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQC2HkhK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQC2HkhK\App_KernelDevDebugContainer([
    'container.build_hash' => 'QC2HkhK',
    'container.build_id' => '315b6b05',
    'container.build_time' => 1707404883,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQC2HkhK');
