<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_font' => [['fontName'], ['_controller' => 'web_profiler.controller.profiler::fontAction'], [], [['text', '.woff2'], ['variable', '/', '[^/\\.]++', 'fontName', true], ['text', '/_profiler/font']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_author_indexauthor' => [[], ['_controller' => 'App\\Controller\\AuthorController::indexAuthor'], [], [['text', '/api/authors']], [], [], []],
    'app_author_createauthor' => [[], ['_controller' => 'App\\Controller\\AuthorController::createAuthor'], [], [['text', '/api/author/create']], [], [], []],
    'app_author_showauthor' => [[], ['_controller' => 'App\\Controller\\AuthorController::showAuthor'], [], [['text', '/api/author/book']], [], [], []],
    'app_book_indexbook' => [[], ['_controller' => 'App\\Controller\\BookController::indexBook'], [], [['text', '/api/books']], [], [], []],
    'app_book_createbook' => [[], ['_controller' => 'App\\Controller\\BookController::createBook'], [], [['text', '/api/book/create']], [], [], []],
    'app_book_showbook' => [['id'], ['_controller' => 'App\\Controller\\BookController::showBook'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/book']], [], [], []],
    'app_book_updatebook' => [['id'], ['_controller' => 'App\\Controller\\BookController::updateBook'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/book/update']], [], [], []],
    'App\Controller\AuthorController::indexAuthor' => [[], ['_controller' => 'App\\Controller\\AuthorController::indexAuthor'], [], [['text', '/api/authors']], [], [], []],
    'App\Controller\AuthorController::createAuthor' => [[], ['_controller' => 'App\\Controller\\AuthorController::createAuthor'], [], [['text', '/api/author/create']], [], [], []],
    'App\Controller\AuthorController::showAuthor' => [[], ['_controller' => 'App\\Controller\\AuthorController::showAuthor'], [], [['text', '/api/author/book']], [], [], []],
    'App\Controller\BookController::indexBook' => [[], ['_controller' => 'App\\Controller\\BookController::indexBook'], [], [['text', '/api/books']], [], [], []],
    'App\Controller\BookController::createBook' => [[], ['_controller' => 'App\\Controller\\BookController::createBook'], [], [['text', '/api/book/create']], [], [], []],
    'App\Controller\BookController::showBook' => [['id'], ['_controller' => 'App\\Controller\\BookController::showBook'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/book']], [], [], []],
    'App\Controller\BookController::updateBook' => [['id'], ['_controller' => 'App\\Controller\\BookController::updateBook'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/book/update']], [], [], []],
];
